                               #cffC6E2FF#b#uFlyFF Version 16 BETA#nb#nu
                              Welcome to FlyFF!

            We hope you enjoy all the new features we have included this time!
If you find any bugs to report, discover you need some extra information, or just feel like chatting about the new version, 
				visit us at:
                     #u#bhttp://flyff-forum.gpotato.com/#nb#nu

   To contact a Game Master regarding in-game issues:
                   #cff0099CC#b#uhttp://flyff.gpotato.com/?m=ticket#nb#nu#nc


Happy FlyFFing,
#bThe FlyFF Game Master Team#nb






